#!/bin/bash

# 设置环境变量抑制TensorFlow AVX警告
export TF_CPP_MIN_LOG_LEVEL=2
export TF_ENABLE_ONEDNN_OPTS=0

# 设置其他有用的环境变量
export CUDA_VISIBLE_DEVICES=0  # 如果有多个GPU，可以指定使用哪个
export PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:128

echo "环境变量设置完成:"
echo "TF_CPP_MIN_LOG_LEVEL=$TF_CPP_MIN_LOG_LEVEL"
echo "TF_ENABLE_ONEDNN_OPTS=$TF_ENABLE_ONEDNN_OPTS"
echo "CUDA_VISIBLE_DEVICES=$CUDA_VISIBLE_DEVICES"
echo "PYTORCH_CUDA_ALLOC_CONF=$PYTORCH_CUDA_ALLOC_CONF"
